### ISSUE TITLE
add utility function to get result rows quickly

### ISSUE THREAD

**Issue by zx9597446** [LukeMauldin/lodbc#2]
some example:
type tRow struct {
    Name string //note field name must export
    Pay  int
    Date string
}
func Query(conn lodbc.IConnection, strQuery string, dst interface{}) []interface{}{
    another := reflect.New(reflect.TypeOf(dst))
    stat, err := conn.NewStatement()
    if err != nil {
        log.Fatal(err)
    }
    defer stat.Close()
    rows, err := stat.Query(strQuery)
    defer rows.Close()
    result := make([]interface{}, 0)

```
for rows.Next() {
    s := reflect.ValueOf(another.Interface()).Elem()
    row := make([]interface{}, s.NumField())
    for i := 0; i < s.NumField(); i++ {
        row[i] = s.Field(i).Addr().Interface()
    }
    err := rows.Scan(row...)
    if err != nil {
        log.Println(err)
    }
    result = append(result, reflect.Indirect(another).Interface())
}
return result
```

}
func main() {
    var r tRow
    result := Query(conn, "select top 1 username, paymoney, sendtime from log_table;", r)
    for _, r := range result {
        fmt.Printf("%v\n", r.(tRow).Name)
    }
}

**Comment by LukeMauldin** [comment]
I like the utility function you created but I think it will need to be updated now because I have converted the driver to use the standard Go database/sql interfaces.  Ideally, your utility function would be included in the Go source tree.  Have you thought about proposing it on go-lang-dev?

**Comment by zx9597446** [comment]
updated function:

func FetchRows(db *sql.DB, query string,  tmplt interface{}) ([]interface{}, error) {
    rows, err := db.Query(query)
    if err != nil {
        return nil, err
    }
    defer rows.Close()
    result := make([]interface{}, 0)
    for rows.Next() {
        s := reflect.ValueOf(tmplt).Elem()
        row := make([]interface{}, s.NumField())
        for i := 0; i < s.NumField(); i++ {
            row[i] = s.Field(i).Addr().Interface()
        }
        err := rows.Scan(row...)
        if err != nil {
            return nil, err
        }
        result = append(result, reflect.Indirect(reflect.ValueOf(tmplt)).Interface())
    }
    return result, nil
}

**Comment by zx9597446** [comment]
and example:

type U struct {
    Username string
    Sum      int
}
func main() {
    db, err := sql.Open("lodbc", "dsn=db;uid=user;pwd=123456")
    if err != nil {
        log.Fatal(err)
    }
    defer db.Close()

```
const sql = "select top %d username, sum(cast(paymoney as int)) as pay from log_table group by username order by pay desc"
rows, err := FetchRows(db, fmt.Sprintf(sql, 100), &U{})
if err != nil {
    log.Fatal(err)
}
for _, row := range rows {
    fmt.Println(row.(U).Username, row.(U).Sum)
}
```

}

**Comment by LukeMauldin** [comment]
Thanks.  I will add this function to the util.go file and you can call it using lodbc.FetchRows...
