### ISSUE TITLE
pls give a example

### ISSUE THREAD

**Issue by lewgun** [LukeMauldin/lodbc#3]
pls give a example to show how to use it

**Comment by LukeMauldin** [comment]
The driver implements the standard Go SQL interfaces so you can use it like any other driver.  Example:

package main

import (
    "database/sql"
    "fmt"
    "github.com/LukeMauldin/lodbc"
    "strings"
)

func main() {
    queryString()
}

func queryString() {
    //Set ODBC driver level
    lodbc.SetODBCVersion(lodbc.ODBCVersion_380)

```
db, err := sql.Open("lodbc", "Driver={SQL Server Native Client 11.0};Server=XXX")
if err != nil {
    fmt.Print(err)
    return
}
defer db.Close()

sqlQuery := `select Data from Mrasystem.dbo.testtable`
row := db.QueryRow(sqlQuery)
var data string
err = row.Scan(&data)
if err != nil && err != sql.ErrNoRows {
    fmt.Printf("Err :%v", err)
    return
}

fmt.Printf("Data len: %v\n", len(data))
```

}
